# -*- coding: utf-8 -*-
"""CNN_kereta_motor.pth

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QTh1Pmj6fCnVPHKJv0XJXzf8Q36SLyz
"""

!pip install torch torchvision pandas numpy matplotlib scikit-learn pillow

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

import zipfile

with zipfile.ZipFile('/dataset kereta.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/kereta')

print("Dataset kereta berjaya dibuka!")

import zipfile

# Buka dataset kereta
with zipfile.ZipFile('/dataset kereta.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/kereta')

# Buka dataset motor
with zipfile.ZipFile('/dataset motor.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/motor')

print("Kedua-dua dataset berjaya dibuka!")

import os

print("Folder kereta:", os.listdir('/content/kereta'))
print("Folder motor:", os.listdir('/content/motor'))

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor()
])

train_data = datasets.ImageFolder(
    '/content/kereta',
    transform=transform
)

test_data = datasets.ImageFolder(
    '/content/motor',
    transform=transform
)

print("Train:", len(train_data))
print("Test:", len(test_data))

import zipfile
import os

with zipfile.ZipFile('/dataset kereta.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset_kereta')

with zipfile.ZipFile('/dataset motor.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset_motor')

print("Kedua-dua dataset berjaya diekstrak!")

import os

print(os.listdir('/content/dataset_kereta'))

import os

print(os.listdir('/content/dataset_kereta/kereta'))

import os

files = os.listdir('/content/dataset_kereta/kereta')

print("Jumlah:", len(files))
print(files)

import os

files = os.listdir('/content/dataset_kereta/kereta')

for i, file in enumerate(files, 1):
    print(i, file)

import os

files = os.listdir('/content/dataset_motor/motor')

print("Jumlah gambar motor:", len(files))

import os

base = "/content/dataset_final"

folders = [
    "train/kereta",
    "train/motor",
    "test/kereta",
    "test/motor"
]

for folder in folders:
    os.makedirs(os.path.join(base, folder), exist_ok=True)

print("Folder train dan test sudah dibuat!")

import os
import shutil

# Lokasi gambar asal
kereta_src = "/content/dataset_kereta/kereta"
motor_src = "/content/dataset_motor/motor"

# Ambil nama fail gambar
kereta = [f for f in os.listdir(kereta_src)
          if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

motor = [f for f in os.listdir(motor_src)
         if f.lower().endswith(('.jpg', '.jpeg', '.png'))]

# 40 untuk train, 10 untuk test
for f in kereta[:40]:
    shutil.copy(os.path.join(kereta_src, f),
                "/content/dataset_final/train/kereta")

for f in kereta[40:50]:
    shutil.copy(os.path.join(kereta_src, f),
                "/content/dataset_final/test/kereta")

for f in motor[:40]:
    shutil.copy(os.path.join(motor_src, f),
                "/content/dataset_final/train/motor")

for f in motor[40:50]:
    shutil.copy(os.path.join(motor_src, f),
                "/content/dataset_final/test/motor")

print("Pembahagian dataset selesai!")
print("Train kereta:", len(os.listdir("/content/dataset_final/train/kereta")))
print("Train motor:", len(os.listdir("/content/dataset_final/train/motor")))
print("Test kereta:", len(os.listdir("/content/dataset_final/test/kereta")))
print("Test motor:", len(os.listdir("/content/dataset_final/test/motor")))

import os

kereta_src = "/content/dataset_kereta/kereta"

files = os.listdir(kereta_src)

print("Jumlah semua fail:", len(files))

for f in files:
    print(f)

import zipfile

zip_path = "/dataset kereta.Zip.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    print("Jumlah fail dalam ZIP:", len(zip_ref.namelist()))
    print("\nIsi ZIP:")
    for f in zip_ref.namelist():
        print(f)

import os

for f in os.listdir('/content'):
    print(f)

import os

print(os.listdir("/content/kereta_baru"))

import os

folder = "/content/kereta_baru/kereta"

files = os.listdir(folder)

print("Jumlah fail dalam folder kereta:", len(files))
print(files)

import os

print(os.listdir("/content"))

import os

print(os.listdir("/content/kereta"))

import os

print(os.listdir("/content/kereta/kereta"))

import os

print("Folder dataset_kereta:")
print(os.listdir("/content/dataset_kereta/kereta"))

import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.lower().endswith(".zip"):
            print(os.path.join(root, file))

import zipfile
import os

zip_path = "/dataset kereta.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    print("Jumlah fail dalam ZIP:", len(zip_ref.namelist()))
    print(zip_ref.namelist()[:10])

import zipfile
import os

zip_path = "/dataset kereta.zip"
extract_path = "/content/kereta_lengkap"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Berjaya extract!")
print("Jumlah gambar:", len(os.listdir("/content/kereta_lengkap/kereta")))

import os

print(os.listdir("/content/kereta_lengkap/kereta"))
print("Jumlah gambar:", len(os.listdir("/content/kereta_lengkap/kereta")))

import os
import shutil

kereta_src = "/content/kereta_lengkap/kereta"

train_kereta = "/content/dataset_final/train/kereta"
test_kereta = "/content/dataset_final/test/kereta"

# Pastikan folder wujud
os.makedirs(train_kereta, exist_ok=True)
os.makedirs(test_kereta, exist_ok=True)

# Ambil semua gambar
kereta = os.listdir(kereta_src)

# 40 gambar untuk training
for f in kereta[:40]:
    shutil.copy(
        os.path.join(kereta_src, f),
        train_kereta
    )

# 10 gambar untuk testing
for f in kereta[40:50]:
    shutil.copy(
        os.path.join(kereta_src, f),
        test_kereta
    )

print("Train kereta:", len(os.listdir(train_kereta)))
print("Test kereta:", len(os.listdir(test_kereta)))

import os

motor_src = "/content/motor/motor"

print("Jumlah gambar motor:", len(os.listdir(motor_src)))

import os
import shutil

motor_src = "/content/motor/motor"

train_motor = "/content/dataset_final/train/motor"
test_motor = "/content/dataset_final/test/motor"

os.makedirs(train_motor, exist_ok=True)
os.makedirs(test_motor, exist_ok=True)

motor = os.listdir(motor_src)

# 40 gambar untuk training
for f in motor[:40]:
    shutil.copy(
        os.path.join(motor_src, f),
        train_motor
    )

# 10 gambar untuk testing
for f in motor[40:50]:
    shutil.copy(
        os.path.join(motor_src, f),
        test_motor
    )

print("Train motor:", len(os.listdir(train_motor)))
print("Test motor:", len(os.listdir(test_motor)))

import os

print("Train kereta:", len(os.listdir("/content/dataset_final/train/kereta")))
print("Train motor:", len(os.listdir("/content/dataset_final/train/motor")))
print("Test kereta:", len(os.listdir("/content/dataset_final/test/kereta")))
print("Test motor:", len(os.listdir("/content/dataset_final/test/motor")))

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

train_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor()
])

train_dataset = datasets.ImageFolder(
    "/content/dataset_final/train",
    transform=train_transform
)

test_dataset = datasets.ImageFolder(
    "/content/dataset_final/test",
    transform=test_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False
)

print("Kelas:", train_dataset.classes)
print("Jumlah data train:", len(train_dataset))
print("Jumlah data test:", len(test_dataset))

import torch
import torch.nn as nn

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1)

        self.pool = nn.MaxPool2d(2, 2)

        self.fc1 = nn.Linear(64 * 16 * 16, 128)
        self.fc2 = nn.Linear(128, 2)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = self.pool(torch.relu(self.conv3(x)))

        x = x.view(x.size(0), -1)

        x = torch.relu(self.fc1(x))
        x = self.fc2(x)

        return x

model = CNN()

print(model)

import torch.optim as optim

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

print("Loss function:", criterion)
print("Optimizer:", optimizer)

num_epochs = 10

train_losses = []
train_accuracies = []

for epoch in range(num_epochs):
    model.train()

    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in train_loader:
        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct / total

    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(
        f"Epoch [{epoch+1}/{num_epochs}] "
        f"Loss: {epoch_loss:.4f} "
        f"Accuracy: {epoch_accuracy:.2f}%"
    )

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total

print(f"Test Accuracy: {test_accuracy:.2f}%")

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total

print(f"Test Accuracy: {test_accuracy:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(train_losses)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import torch

class_names = train_dataset.classes

model.eval()

images, labels = next(iter(test_loader))

with torch.no_grad():
    outputs = model(images)
    _, predictions = torch.max(outputs, 1)

plt.figure(figsize=(12, 8))

for i in range(min(8, len(images))):
    image = images[i].permute(1, 2, 0)

    plt.subplot(2, 4, i + 1)
    plt.imshow(image)
    plt.title(
        f"Actual: {class_names[labels[i]]}\n"
        f"Pred: {class_names[predictions[i]]}"
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

!pip install scikit-learn

from sklearn.metrics import classification_report

model.eval()

all_labels = []
all_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predictions = torch.max(outputs, 1)

        all_labels.extend(labels.numpy())
        all_predictions.extend(predictions.numpy())

print(classification_report(
    all_labels,
    all_predictions,
    target_names=class_names
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels, all_predictions)

plt.figure(figsize=(6, 5))
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(
    range(len(class_names)),
    class_names
)

plt.yticks(
    range(len(class_names)),
    class_names
)

for i in range(len(class_names)):
    for j in range(len(class_names)):
        plt.text(j, i, cm[i, j],
                 ha="center",
                 va="center")

plt.colorbar()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

def create_model():
    return CNN()

experiments = [
    {"lr": 0.001, "batch_size": 8},
    {"lr": 0.0005, "batch_size": 8},
    {"lr": 0.001, "batch_size": 16}
]

results = []

for exp in experiments:

    print("\n==============================")
    print("Learning Rate:", exp["lr"])
    print("Batch Size:", exp["batch_size"])
    print("==============================")

    train_loader_exp = DataLoader(
        train_dataset,
        batch_size=exp["batch_size"],
        shuffle=True
    )

    test_loader_exp = DataLoader(
        test_dataset,
        batch_size=exp["batch_size"],
        shuffle=False
    )

    model_exp = create_model()

    criterion_exp = nn.CrossEntropyLoss()

    optimizer_exp = optim.Adam(
        model_exp.parameters(),
        lr=exp["lr"]
    )

    # Training
    for epoch in range(10):

        model_exp.train()

        for images, labels in train_loader_exp:

            optimizer_exp.zero_grad()

            outputs = model_exp(images)

            loss = criterion_exp(
                outputs,
                labels
            )

            loss.backward()

            optimizer_exp.step()

    # Testing
    model_exp.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in test_loader_exp:

            outputs = model_exp(images)

            _, predicted = torch.max(
                outputs,
                1
            )

            total += labels.size(0)

            correct += (
                predicted == labels
            ).sum().item()

    accuracy = 100 * correct / total

    results.append({
        "Learning Rate": exp["lr"],
        "Batch Size": exp["batch_size"],
        "Test Accuracy (%)": accuracy
    })

    print(
        f"Test Accuracy: {accuracy:.2f}%"
    )

import pandas as pd

results_df = pd.DataFrame(results)

print(results_df)

plt.figure(figsize=(8,5))

labels = [
    f"LR={row['Learning Rate']}, BS={row['Batch Size']}"
    for _, row in results_df.iterrows()
]

plt.bar(
    labels,
    results_df["Test Accuracy (%)"]
)

plt.xlabel("Hyperparameter")
plt.ylabel("Test Accuracy (%)")
plt.title("Perbandingan Hyperparameter")
plt.xticks(rotation=20)
plt.show()

torch.save(
    model.state_dict(),
    "/content/cnn_kereta_motor.pth"
)

print("Model berjaya disimpan.")

import json

with open("/content/classes.json", "w") as f:
    json.dump(class_names, f)

print("Nama kelas:", class_names)

import numpy as np
import pandas as pd

data = np.array(train_accuracies)

accuracy_df = pd.DataFrame({
    "Epoch": np.arange(1, len(data) + 1),
    "Training Accuracy (%)": data
})

print(accuracy_df)

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total

print(f"Test Accuracy: {test_accuracy:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(train_losses, marker='o')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.grid()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(train_accuracies, marker='o')
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training Accuracy")
plt.grid()
plt.show()

from sklearn.metrics import classification_report

model.eval()

all_labels = []
all_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predictions = torch.max(outputs, 1)

        all_labels.extend(labels.numpy())
        all_predictions.extend(predictions.numpy())

print(classification_report(
    all_labels,
    all_predictions,
    target_names=train_dataset.classes
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels, all_predictions)

plt.figure(figsize=(6,5))
plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(
    range(len(train_dataset.classes)),
    train_dataset.classes
)

plt.yticks(
    range(len(train_dataset.classes)),
    train_dataset.classes
)

for i in range(len(train_dataset.classes)):
    for j in range(len(train_dataset.classes)):
        plt.text(
            j, i, cm[i, j],
            ha="center",
            va="center"
        )

plt.colorbar()
plt.show()

import matplotlib.pyplot as plt

model.eval()

images, labels = next(iter(test_loader))

with torch.no_grad():
    outputs = model(images)
    _, predictions = torch.max(outputs, 1)

plt.figure(figsize=(12,8))

for i in range(min(8, len(images))):

    image = images[i].permute(1, 2, 0)

    plt.subplot(2,4,i+1)

    plt.imshow(image)

    plt.title(
        f"Actual: {train_dataset.classes[labels[i]]}\n"
        f"Pred: {train_dataset.classes[predictions[i]]}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

experiments = [
    {"lr": 0.001, "batch_size": 8},
    {"lr": 0.0005, "batch_size": 8},
    {"lr": 0.001, "batch_size": 16}
]

results = []

for exp in experiments:

    print("\n==============================")
    print("Learning Rate:", exp["lr"])
    print("Batch Size:", exp["batch_size"])
    print("==============================")

    train_loader_exp = DataLoader(
        train_dataset,
        batch_size=exp["batch_size"],
        shuffle=True
    )

    test_loader_exp = DataLoader(
        test_dataset,
        batch_size=exp["batch_size"],
        shuffle=False
    )

    model_exp = CNN()

    criterion_exp = nn.CrossEntropyLoss()

    optimizer_exp = optim.Adam(
        model_exp.parameters(),
        lr=exp["lr"]
    )

    for epoch in range(10):

        model_exp.train()

        for images, labels in train_loader_exp:

            optimizer_exp.zero_grad()

            outputs = model_exp(images)

            loss = criterion_exp(
                outputs,
                labels
            )

            loss.backward()

            optimizer_exp.step()

    model_exp.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in test_loader_exp:

            outputs = model_exp(images)

            _, predicted = torch.max(
                outputs, 1
            )

            total += labels.size(0)

            correct += (
                predicted == labels
            ).sum().item()

    accuracy = 100 * correct / total

    results.append({
        "Learning Rate": exp["lr"],
        "Batch Size": exp["batch_size"],
        "Test Accuracy (%)": accuracy
    })

    print(
        f"Test Accuracy: {accuracy:.2f}%"
    )

import pandas as pd

results_df = pd.DataFrame(results)

results_df

import matplotlib.pyplot as plt

labels = [
    f"LR={row['Learning Rate']}, BS={row['Batch Size']}"
    for _, row in results_df.iterrows()
]

plt.figure(figsize=(8,5))

plt.bar(
    labels,
    results_df["Test Accuracy (%)"]
)

plt.xlabel("Hyperparameter")
plt.ylabel("Test Accuracy (%)")
plt.title("Perbandingan Hyperparameter")
plt.xticks(rotation=20)

plt.show()

torch.save(
    model.state_dict(),
    "/content/cnn_kereta_motor.pth"
)

print("Model berjaya disimpan.")

import json

class_names = train_dataset.classes

with open("/content/classes.json", "w") as f:
    json.dump(class_names, f)

print("Kelas:", class_names)

import numpy as np
import pandas as pd

accuracy_array = np.array(train_accuracies)

accuracy_df = pd.DataFrame({
    "Epoch": np.arange(1, len(accuracy_array) + 1),
    "Training Accuracy (%)": accuracy_array
})

accuracy_df

from sklearn.metrics import classification_report

model.eval()

all_labels = []
all_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predictions = torch.max(outputs, 1)

        all_labels.extend(labels.numpy())
        all_predictions.extend(predictions.numpy())

print(classification_report(
    all_labels,
    all_predictions,
    target_names=train_dataset.classes
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels, all_predictions)

plt.figure(figsize=(6,5))
plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(range(len(train_dataset.classes)), train_dataset.classes)
plt.yticks(range(len(train_dataset.classes)), train_dataset.classes)

for i in range(len(train_dataset.classes)):
    for j in range(len(train_dataset.classes)):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.colorbar()
plt.show()

model.eval()

images, labels = next(iter(test_loader))

with torch.no_grad():
    outputs = model(images)
    _, predictions = torch.max(outputs, 1)

plt.figure(figsize=(12, 8))

for i in range(min(8, len(images))):
    image = images[i].permute(1, 2, 0)

    plt.subplot(2, 4, i + 1)
    plt.imshow(image)

    plt.title(
        f"Actual: {train_dataset.classes[labels[i]]}\n"
        f"Pred: {train_dataset.classes[predictions[i]]}"
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

# Hyperparameter Tuning

from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
import pandas as pd

experiments = [
    {"lr": 0.001, "batch_size": 8},
    {"lr": 0.0005, "batch_size": 8},
    {"lr": 0.001, "batch_size": 16}
]

results = []

for exp in experiments:

    print("====================================")
    print("Learning Rate:", exp["lr"])
    print("Batch Size:", exp["batch_size"])

    # DataLoader
    train_loader_exp = DataLoader(
        train_dataset,
        batch_size=exp["batch_size"],
        shuffle=True
    )

    test_loader_exp = DataLoader(
        test_dataset,
        batch_size=exp["batch_size"],
        shuffle=False
    )

    # Model baru
    model_exp = CNN()

    # Loss
    criterion_exp = nn.CrossEntropyLoss()

    # Optimizer
    optimizer_exp = optim.Adam(
        model_exp.parameters(),
        lr=exp["lr"]
    )

    # Training
    for epoch in range(10):

        model_exp.train()

        for images, labels in train_loader_exp:

            optimizer_exp.zero_grad()

            outputs = model_exp(images)

            loss = criterion_exp(outputs, labels)

            loss.backward()

            optimizer_exp.step()

    # Testing
    model_exp.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in test_loader_exp:

            outputs = model_exp(images)

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total

    print(f"Test Accuracy: {accuracy:.2f}%")

    results.append({
        "Learning Rate": exp["lr"],
        "Batch Size": exp["batch_size"],
        "Test Accuracy (%)": accuracy
    })


# Paparkan keputusan dalam jadual
results_df = pd.DataFrame(results)

print("\nKEPUTUSAN HYPERPARAMETER TUNING")
print(results_df)

import matplotlib.pyplot as plt

labels = [
    f"LR={row['Learning Rate']}\nBS={row['Batch Size']}"
    for _, row in results_df.iterrows()
]

accuracies = results_df["Test Accuracy (%)"]

plt.figure(figsize=(8,5))

plt.bar(labels, accuracies)

plt.xlabel("Hyperparameter")
plt.ylabel("Test Accuracy (%)")
plt.title("Perbandingan Hyperparameter Tuning")

for i, value in enumerate(accuracies):
    plt.text(i, value + 0.5, f"{value:.2f}%", ha="center")

plt.ylim(0, 100)
plt.show()

# Simpan model CNN
torch.save(model.state_dict(), "/content/cnn_kereta_motor.pth")

print("Model berjaya disimpan!")

import json

class_names = train_dataset.classes

with open("/content/classes.json", "w") as f:
    json.dump(class_names, f)

print("Class names:", class_names)

import json

class_names = train_dataset.classes

with open("/content/classes.json", "w") as f:
    json.dump(class_names, f)

print(class_names)